django-project/myapp/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('', views.IndexMain.as_view()),
]

django-project/myapp/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    # user/
    path('register/', views.Registration.as_view(), name='register'),
    # 로그인
    path('login/', views.Login.as_view(), name='login'),
    # 로그아웃
    path('logout/', views.Logout.as_view(), name='logout'),
]

django-project/myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>
        {%block title%}{{title}}{%endblock%}
    </title>
</head>
<body>
    <div class="container">
        {% if user.is_authenticated %}
        <p>Welcome, {{ user.email }}</p>
        <a href="{% url 'user:logout' %}" class="btn">Logout</a>
        {% else %}
        <p>Please, Login</p>
        <a href="{% url 'user:login' %}" class="btn">Login</a>
        {% endif %}
        <h1>Blog</h1>
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</body>
</html>

django-project/myapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{%load i18n%}
{% comment %} {% static '' %} {% endcomment %}

{%block content%}
    <h1>Index page</h1>
    <h2>{% trans "welcome" %}</h2>
    <a href="{%url 'user:register'%}" class="btn">회원가입</a>
    <a href="{%url 'user:login'%}" class="btn">로그인</a>
{%endblock%}
<link href="{% static 'blog/static/css/login-join.css' %}" rel="stylesheet" />