django-project/myapp/app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
    path('', views.IndexMain.as_view()),
]

django-project/myapp/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # 글 조회
    path("",views.Index.as_view(), name='list'), 
    # 글 상세조회
    path("detail/<int:pk>/", views.DetailView.as_view(), name='detail' ),
    #글 작성
    path("write/", views.Write.as_view(), name='write'),
    #글 수정
    path("detail/<int:pk>/edit/", views.Update.as_view(), name='edit'),
    #글 삭제
    path("detail/<int:pk>/delete/", views.Delete.as_view(), name='delete'),
    #코멘트 작성
    path("detail/<int:pk>/comment/write", views.CommentWrite.as_view(), name='cm-write'),
    #코멘트 삭제
    path("detail/comment/<int:pk>/delete", views.CommentDelete.as_view(), name='cm-delete'),
    # 태그 작성
    path("detail/<int:pk>/hashtag/write/", views.HashTagWrite.as_view(), name='tag-write'),
    # 태그 삭제
    path("detail/hashtag/<int:pk>/delete/", views.HashTagDelete.as_view(), name='tag-delete'),
]

django-project/myapp/blog/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField() 
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True) 
    update_at = models.DateTimeField(auto_now=True) 


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE) 
    content = models.TextField()
    writer = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self): 
        return self.content


class HashTag(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    writer = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    

django-project/myapp/blog/forms.py
from django import forms
from .models import Post, Comment, HashTag

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'content']


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']
        widgets ={
            'content': forms.Textarea(attrs={'rows':'2', 'cols':'35'})
        }


class HashTagForm(forms.ModelForm):

    class Meta:
        model = HashTag
        fields = ['name']

django-project/myapp/blog/views.py
from django.shortcuts import render, redirect 
from typing import Any
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from .models import Post, Comment, HashTag
from .forms import PostForm, CommentForm, HashTagForm



# Create your views here.
class Index(View):
    
    def get(self, request):
        posts = Post.objects.all()
        context = {
            "posts": posts,
            "title": "Blog"
        }
        return render(request, 'blog/post_list.html', context)


class Write(LoginRequiredMixin, View):
    redirect_field_name='next'
    def get(self, request):
        next_path = request.GET.get('next')
        form = PostForm()
        context = {
            'form':form,
            'title': 'Blog'
        }
        return render(request, 'blog/post_form.html', context)
    def post(self, request):
        form = PostForm(request.POST) 
        if form.is_valid(): 
            post=form.save(commit=False)
            post.writer= request.user 
            post.save()
            return redirect('blog:list')
        form.add_error(None, '폼이 유효하지 않습니다')
        context={
            'form': form
        }
        return render(request, 'blog/post_form.html', context)


class DetailView(View):
    def get(self, request, pk): 
        post = Post.objects.prefetch_related('comment_set', 'hashtag_set').get(pk=pk)
        comments = post.comment_set.all()
        hashtags = post.hashtag_set.all()
        comment_form = CommentForm()
        hashtag_form = HashTagForm()
        context = {
            "title": "Blog",
            'post_id': pk,
            'post_title': post.title,
            'post_content': post.content,
            'post_writer': post.writer,
            'post_created_at': post.created_at,
            'comments': comments,
            'hashtags': hashtags,
            'comment_form': comment_form,
            'hashtag_form': hashtag_form,
        }
        return render(request, 'blog/post_detail.html', context)


class Update(View):
    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        form = PostForm(initial={'title':post.title, 'content':post.content})
        context={
            'form':form,
            'post':post,
            'title': 'Blog'
        }
        return render(request, 'blog/post_edit.html', context)
    
    def post(self, request, pk):
        try:
            post = Post.objects.get(pk=pk)
        except ObjectDoesNotExist as e:
            print('Post does not exist.', str(e))
        
        form = PostForm(request.POST)
        if form.is_valid():
            post.title = form.cleaned_data['title']
            post.content = form.cleaned_data['content']
            post.save()
            return redirect('blog:detail', pk=pk)
        context = {
            'form': form,
            "title": "Blog"
        }
        return render(request, 'blog/post_edit.html',context)


class Delete(View):
    def post(self, request, pk): # post_id
        ## try, except
        try:
            post = Post.objects.get(pk=pk)
        except ObjectDoesNotExist as e:
            print('Post does not exist.', str(e))
        
        post.delete()
        return redirect('blog:list')


class CommentWrite(View):
    def post(self, request, pk):
        form = CommentForm(request.POST)
        try:
            post = Post.objects.get(pk=pk) 
        except ObjectDoesNotExist as e:
            print('Post does not exist.', str(e))
        if form.is_valid(): 
            content = form.cleaned_data['content']
            writer=request.user
            try:
                comment = Comment.objects.create(post=post, content=content, writer=writer)
            except ObjectDoesNotExist as e:
                print('Post does not exist', str(e))
            except ValidationError as e:
                print('Validation error occurred', str(e))
            return redirect('blog:detail', pk=pk)
        hashtag_form = HashTagForm()
        context = {
            "title": "Blog",
            'post_id': pk,
            'comments': post.comment_set.all(),
            'hashtags': post.hashtag_set.all(),
            'comment_form': form,
            'hashtag_form': hashtag_form
        }
        return render(request, 'blog/post_detail.html', context)


class CommentDelete(View):
    def post(self, request, pk): 
        try:
            comment = Comment.objects.get(pk=pk)
        except ObjectDoesNotExist as e:
            print('Comment does not exist.', str(e))
        post_id = comment.post.id
        comment.delete()
        return redirect('blog:detail', pk=post_id)


class HashTagWrite(View):
    def post(self, request, pk):
        form = HashTagForm(request.POST)
        try:
            post = Post.objects.get(pk=pk)
        except ObjectDoesNotExist as e:
            print('Comment does not exist.', str(e))
        if form.is_valid():
            name = form.cleaned_data['name']
            writer=request.user
            try:
                hashtag = HashTag.objects.create(post=post, name=name, writer=writer)    
            except ObjectDoesNotExist as e:
                print('Post does not exist.', str(e))
            except ValidationError as e:
                print('Valdation error occurred', str(e))
            return redirect('blog:detail', pk=pk)
        comment_form = CommentForm()
        context={
            'title': 'Blog',
            'post_id':pk,
            'comments':post.comment_set.all(),
            'hashtags':post.hashtag_set.all(),
            'comment_form':comment_form,
            'hashtag_form': form
        }
        return render(request, 'blog/post_detail.html', context)


class HashTagDelete(View):
    def post(self, request, pk):
        try:
            hashtag = HashTag.objects.get(pk=pk)
        except ObjectDoesNotExist as e:
            print('HashTag does not exist.', str(e))
        post_id = hashtag.post.id
        hashtag.delete()
        return redirect('blog:detail', pk=post_id)

django-project/myapp/blog/templates/blog/form_error.html
<!-- form error 출력 -->

<div class="alert alert-danger">
    {{ form }}
</div>

django-project/myapp/blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/view.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <div class="main">
        <h2 class="main-title">제목: {{ post_title }}</h2>
    
        <div class="btn-group" >
            {% if post_writer == request.user %}
            <a href="{% url 'blog:edit' pk=post_id %}" class="btn">수정</a>
            <form action="{% url 'blog:delete' pk=post_id%}" method="post">
                {% csrf_token %}
                <button type="submit"  class="btn">삭제</button>
            </form>
            {% endif %}
        </div>
    
        <div class="view">
            <div class="view-header">
                <p>내용: {{ post_content }}</p>
                <p>작성자: {{ post_writer }}</p>
                <p>작성일: {{ post_created_at }}</p>
            </div>
            <hr>
        
            <!-- 작성 화면 -->
            <div class="view-info">
                <h3>댓글</h3>
                <form action="{% url 'blog:cm-write' pk=post_id %}" method="post">
                    {% csrf_token %}
                    {% if comment_form.errors %}
                        {% with form=comment_form %}
                            {% include 'blog/form_error.html' %}
                        {% endwith %}
                    {% else %}
                        {{ comment_form.content }}
                    {% endif %}
                    <input type="submit" value="댓글 작성">
                </form>
                <br>
                <!-- comments -->
                <!-- if 문 -->
                {% if comments %}
                    <!-- for 문 -->
                    <ul>
                        {% for comment in comments %}
                        <!-- 내용, 작성시간, 삭제 버튼 -->
                            <li>{{ comment.content }} / {{ comment.created_at }}
                                {% if comment.writer == request.user %}
                                    <form action="{% url 'blog:cm-delete' pk=comment.pk %}" method="post">
                                        {% csrf_token %}
                                        <input type="submit" value="X" class='btn'>
                                    </form>
                                {% endif %}
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <p>댓글이 없습니다.</p>
                {% endif %}
                <hr>
                <!-- 태그작성 화면 -->
                <h3>해시태그</h3>
                <form action="{% url 'blog:tag-write' pk=post_id %}" method="post">
                    {% csrf_token %}
                    {% if hashtag_form.errors %}
                        {% with form=hashtag_form %}
                            {% include 'blog/form_error.html' %}
                        {% endwith %}
                    {% else %}
                        {{ hashtag_form.name }}
                    {% endif %}
                    <input type="submit" value="태그 작성">
                </form>
                {% if hashtags %}
                <ul>
                    {% for hashtag in hashtags %}
                    <li>
                        {{ hashtag }}
                        {% if hashtag.writer == request.user %}
                            <form action="{% url 'blog:tag-delete' pk=hashtag.pk %}" method="post">
                                {% csrf_token %}
                                <input type="submit" value="X" class='btn'>
                            </form>
                        {% endif %}
                    </li>
                    {% endfor %}
                </ul>
                {% else %}
                <br>
                <p>해시태그가 없습니다.</p>
                {% endif %}
            </div>
        </div>
    </div>
<!-- footer -->
<p class="footer">Copyright 2023. backend ormi is good choice.</p>
<!-- //footer -->


{% endblock %}

django-project/myapp/blog/templates/blog/post_edit.html
{% extends 'base.html' %}
{%load i18n%}
{% block content %}

{% if form.errors %}
    {% include 'blog/form_error.html' %}
{% else %}
    {% trans "welcome" %}
    <form action="{% url 'blog:edit' pk=post.pk%}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value = "수정">
    </form>
{% endif %}
{% endblock %}

django-project/myapp/blog/templates/blog/post_form.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/view.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/table.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
    <p>블로그 글 작성 화면</p>
    
    <!-- 내용 -->
    <form action="{%url 'blog:write'%}" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" class="btn btn-outline-success">
    </form>
{% endblock %}

django-project/myapp/blog/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'css/view.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/table.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/list.css' %}">
<div class="main">
    <p class="main-title">블로그 게시판 첫 화면 입니다.</p>
    <div class="board-top">
        <p class="main-desc"><strong>2개</strong>의 게시글이 있습니다.</p>
    
        <div>
            <label for="category" class="a11y-hidden">카테고리</label>
            <select id="category">
                <option>전체</option>
                <option>공지사항</option>
                <option>일반</option>
            </select>
            <form class="search-form">
                <label for="search" class="a11y-hidden">검색</label>
                <input id="search" type="search" placeholder="검색어를 입력해주세요">
                <button type="submit">
                <img src="./img/icon-search.png" alt="검색">
                </button>
            </form>

            <label for="sort" class="a11y-hidden">정렬</label>
            <select id="sort">
                <option>조회순</option>
                <option>최신순</option>
            </select>
        </div>
    </div>
    <form action="{% url 'blog:write' %}" method="get">
        <input type="hidden" name="{{ redirect_field_name }}" value="{{ request.GET.next }}">
        <input type="submit" value="글 작성">
    </form>
    <!-- 글이 있을때 -->
    <!-- 테이블 -->
    <!-- 조건문 -->
    {%if posts%}
        <table class="table list">
            <colgroup>
                <col style="width: 40px">
                <col style="width: 60px">
                <col>
                <col style="width: 100px">
                <col style="width: 120px">
                <col style="width: 100px">
            </colgroup>
            <thead class="table-dark">
                <tr>
                    <th>
                        <input type="checkbox" id="all-article">
                        <!-- <label for="all-article">페이지 전체 게시글 선택</label> -->
                    </th>
                    <th>번호</th>
                    <th>제목</th>
                    <th>내용</th>
                    <th>작성자</th>
                    <th>조회수</th>
                </tr>
            </thead>
            <tbody>
                {% for post in posts %}
                    <tr>
                        <td>
                            <input type="checkbox" id="all-article">
                        </td>
                        <td>{{post.pk}}</td>
                        
                        <td>
                            <a href="{% url 'blog:detail' pk=post.pk %}">{{post.title}}</a>
                        </td>
                        <td>
                            <a href="{% url 'blog:detail' pk=post.pk %}">{{post.content}}</a>
                        </td>
                        <td>{{post.writer}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="board-bottom">
            <!-- 페이지 -->
            <div class="pagination">
                <a href="#"><img src="../static/asset/img/first.png" alt="첫번째 페이지"></a>
                <a href="#"><img src="../static/asset/img/prev.png" alt="이전 페이지"></a>
                <a href="#" class="num active">1</a>
                <a href="#" class="num">2</a>
                <a href="#" class="num">3</a>
                <a href="#" class="num">4</a>
                <a href="#" class="num">5</a>
                <a href="#"><img src="../static/asset/img/next.png" alt="첫번째 페이지"></a>
                <a href="#"><img src="../static/asset/img/last.png" alt="이전 페이지"></a>
                </div>
                <!-- //페이지 -->
            </div>
    {%else%}
    <!-- 글이 없을때 문구 출력 -->
        <p>작성된 게시물이 없습니다</p>
    {%endif%}
    <!-- footer -->
    <p class="footer">Copyright 2023. Chilli All rights reserved.</p>
    <!-- //footer -->
</div>

{% endblock %}